CloneCoding_Pinterest/accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path("hello_world/", hello_world, name="hello_world"),

    path("login/", LoginView.as_view(template_name='accountapp/login.html'), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),

    # CBV는 .as_view
    path('create/', AccountCreateView.as_view(), name="create"),
    path('detail/<int:pk>', AccountDetailView.as_view(), name="detail"),
    path('update/<int:pk>', AccountUpdateView.as_view(), name="update"),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name="delete"),
]

CloneCoding_Pinterest/pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path("admin/", admin.site.urls),
    path("accounts/", include('accountapp.urls')),
    path("profiles/", include('profileapp.urls')),
    path("articles/", include('articleapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CloneCoding_Pinterest/profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

CloneCoding_Pinterest/accountapp/models.py
from django.db import models

# Create your models here.

class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

CloneCoding_Pinterest/accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from accountapp.decorators import account_ownership_required
from accountapp.form import AccountUpdateForm
from accountapp.models import HelloWorld


# Create your views here.

# 함수형 view
@login_required
def hello_world(request):

    if request.method == "POST":

        temp = request.POST.get('hello_world_input')

        new_hello_world = HelloWorld()
        new_hello_world.text = temp
        new_hello_world.save()

        hello_world_list = HelloWorld.objects.all()
        return HttpResponseRedirect(reverse('accountapp:hello_world'))

    else:
        hello_world_list = HelloWorld.objects.all()
        return render(request, 'accountapp/hello_world.html', context={'hello_world_list': hello_world_list})



has_ownership = [account_ownership_required, login_required]
# Class형 View
class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/create.html'

class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

    def get(self, *arg, **kwargs):
        if self.request.user.is_authenticated and self.get_object() == self.request.user:
            return super().get(*arg, **kwargs)
        else:
            return HttpResponseForbidden()

    def post(self, *arg, **kwargs):
        if self.request.user.is_authenticated:
            return super().get(*arg, **kwargs)
        else:
            return HttpResponseForbidden()

@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
@method_decorator(account_ownership_required, 'get')
@method_decorator(account_ownership_required, 'post')
class AccountUpdateView(UpdateView):
    model = User
    context_object_name = 'target_user'
    form_class = AccountUpdateForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/update.html'

    def get(self, *arg, **kwargs):
        if self.request.user.is_authenticated and self.get_object() == self.request.user:
            return super().get(*arg, **kwargs)
        else:
            return HttpResponseForbidden()

    def post(self, *arg, **kwargs):
        if self.request.user.is_authenticated:
            return super().get(*arg, **kwargs)
        else:
            return HttpResponseForbidden()

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

CloneCoding_Pinterest/accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

  <div  style="text-align: center; max-width: 500px; margin: 4rem auto">

    <div class="mb-4">
      <h4>Sign Up</h4>
    </div>
    <form action="{% url 'accountapp:create' %}" method="post">
      {% csrf_token %}
        <!-- {{ form }} -->
        {% bootstrap_form form %}
      <input type="submit"  class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
  </div>


{% endblock %}

CloneCoding_Pinterest/accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

  <div  style="text-align: center; max-width: 500px; margin: 4rem auto">

    <div class="mb-4">
      <h4>Quit</h4>
    </div>
    <form action="{% url 'accountapp:delete' target_user.pk %}" method="post">
      {% csrf_token %}

      <input type="submit"  class="btn btn-danger rounded-pill col-6 mt-3">
    </form>
  </div>


{% endblock %}

CloneCoding_Pinterest/accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

  <div>
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">

      {% if target_user.profile %}

        <img src="{{ target_user.profile.image.url }}" alt=""
             style="height: 12rem; width: 12rem; border-radius: 20rem; margin-bottom: 2rem;">

        <h2 style="font-family: 'NanumSquareB'">
          {% if target_user == user %}
            {{ target_user.profile.nickname }}
            <a href="{% url 'profileapp:update' target_user.profile.pk %}">
              edit
            </a>
          {% endif %}
        </h2>

        <h5 style="margin-bottom: 3rem;">
          {{ target_user.profile.message }}
        </h5>

      {% else %}

        {% if target_user == user %}
          <a href="{% url 'profileapp:create' %}">
            <h2 style="font-family: 'NanumSquareB'">
              Create Profile
            </h2>
          </a>
        {% else %}

        <h2>
          닉네임 미설정
        </h2>

        {% endif %}


      {% endif %}



      {% if target_user == user %}
      <a href="{% url 'accountapp:update' user.pk %}">
        <p>
          Change Info
        </p>
      </a>
      <a href="{% url 'accountapp:delete' user.pk %}">
        <p>
          Quit
        </p>
      </a>
      {% endif %}


    </div>
  </div>


{% endblock %}

CloneCoding_Pinterest/accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}

{% block content %}

    <div style="border-radius: 1rem; margin: 2rem; text-align: center">
      <h1 style="font-family: 'lobster', cursive;">
        Hello world LIST!
      </h1>

        <form action="/accounts/hello_world/" method="post">
            {% csrf_token %}
            <div>
                <input type="text" name="hello_world_input">
            </div>
            <div>
                <input type="submit" class="btn btn-primary" value="POST">
            </div>

        </form>

        {% if hello_world_list %}
            {% for hello_world in hello_world_list %}

            <h4>
                {{ hello_world.text }}
            </h4>

            {% endfor %}
        {% endif %}

    </div>

{% endblock %}

CloneCoding_Pinterest/accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

  <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div>
      <h4>Login</h4>
    </div>
    <div>
      <form action="" method="post">
        {% csrf_token %}
        <!-- {{ form }} -->
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
      </form>
    </div>

  </div>


{% endblock %}

CloneCoding_Pinterest/accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

  <div  style="text-align: center; max-width: 500px; margin: 4rem auto">

    <div class="mb-4">
      <h4>Change Info</h4>
    </div>
    <form action="{% url 'accountapp:update' target_user.pk %}" method="post">
      {% csrf_token %}
        <!-- {{ form }} -->
        {% bootstrap_form form %}
      <input type="submit"  class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
  </div>


{% endblock %}