CloneCoding_Pinterest/accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path("hello_world/", hello_world, name="hello_world"),

    path("login/", LoginView.as_view(template_name='accountapp/login.html'), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),

    # CBV는 .as_view
    path('create/', AccountCreateView.as_view(), name="create"),
    path('detail/<int:pk>', AccountDetailView.as_view(), name="detail"),
    path('update/<int:pk>', AccountUpdateView.as_view(), name="update"),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name="delete"),
]

CloneCoding_Pinterest/articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView

app_name = "articleapp"

urlpatterns = [
    path('list/', TemplateView.as_view(template_name='articleapp/list.html'), name='list'),
    path('create/', ArticleCreateView.as_view(template_name='articleapp/create.html'), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(template_name='articleapp/detail.html'), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(template_name='articleapp/update.html'), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(template_name='articleapp/delete.html'), name='delete'),
]

CloneCoding_Pinterest/pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path("admin/", admin.site.urls),
    path("accounts/", include('accountapp.urls')),
    path("profiles/", include('profileapp.urls')),
    path("articles/", include('articleapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CloneCoding_Pinterest/articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)

    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)

    created_at = models.DateField(auto_now_add=True, null=True)

CloneCoding_Pinterest/articleapp/forms.py
from django.forms import ModelForm

from articleapp.models import Article


class ArticleCreationForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'image', 'content']

CloneCoding_Pinterest/articleapp/views.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from articleapp.decorators import article_ownership_required
from articleapp.forms import ArticleCreationForm
from articleapp.models import Article


# Create your views here.


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleCreationForm
    template_name = 'articleapp/create.html'

    def form_valid(self, form):
        temp_article = form.save(commit=False)
        temp_article.writer = self.request.user
        temp_article.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})

class ArticleDetailView(DetailView):
    model = Article
    context_object_name = 'target_article'
    template_name = 'articleapp/detail.html'

@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleUpdateView(UpdateView):
    model = Article
    context_object_name = 'target_article'
    form_class = ArticleCreationForm
    template_name = 'articleapp/update.html'

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})

@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleDeleteView(DeleteView):
    model = Article
    context_object_name = 'target_article'
    success_url = reverse_lazy('articleapp:list')
    template_name = 'articleapp/delete.html'

CloneCoding_Pinterest/articleapp/templates/articleapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

  <div  style="text-align: center; max-width: 500px; margin: 4rem auto">

    <div class="mb-4">
      <h4>Article Create</h4>
    </div>
    <form action="{% url 'articleapp:create' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
        <!-- {{ form }} -->
        {% bootstrap_form form %}
      <input type="submit"  class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
  </div>


{% endblock %}

CloneCoding_Pinterest/articleapp/templates/articleapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

  <div  style="text-align: center; max-width: 500px; margin: 4rem auto">

    <div class="mb-4">
      <h4>Delete Article {{ target_article.title }} </h4>
    </div>
    <form action="{% url 'accountapp:delete' target_article.pk %}" method="post">
      {% csrf_token %}

      <input type="submit"  class="btn btn-danger rounded-pill col-6 mt-3">
    </form>
  </div>


{% endblock %}

CloneCoding_Pinterest/articleapp/templates/articleapp/detail.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

  <div>
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">

      <h1>
        {{ target_article.title }}
      </h1>

      <img src="{{ target_article.image.url }}" alt="">

      <p>
        {{ target_article.content }}
      </p>

      <a href="{% url 'articleapp:update' pk=target_article.pk %}">
        <p>Update Article</p>
      </a>
      <a href="{% url 'articleapp:delete' pk=target_article.pk %}">
        <p>Delete Article</p>
      </a>

    </div>
  </div>

{% endblock %}

CloneCoding_Pinterest/articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <style>
      .container div {
        width: 250px;
        background-color: antiquewhite;
        display: flex;
        justify-content: center;
        align-items: center;
        border-radius: 1rem;
      }

      .container img {
        width: 100%;
        border-radius: 1rem;
      }

  </style>


    <div class="container">
      <div class="item1">
        <img src="https://picsum.photos/200/300" alt="">
      </div>
      <div class="item2">
        <img src="https://picsum.photos/200/340" alt="">
      </div>
      <div class="item3">
        <img src="https://picsum.photos/200/260" alt="">
      </div>
      <div class="item4">
        <img src="https://picsum.photos/200/400" alt="">
      </div>
      <div class="item5">
        <img src="https://picsum.photos/200/510" alt="">
      </div>
      <div class="item6">
        <img src="https://picsum.photos/200/300" alt="">
      </div>
      <div class="item7">
        <img src="https://picsum.photos/200/250" alt="">
      </div>
      <div class="item8">
        <img src="https://picsum.photos/200/440" alt="">
      </div>
      <div class="item9">
        <img src="https://picsum.photos/200/320" alt="">
      </div>
      <div class="item10">
        <img src="https://picsum.photos/200/300" alt="">
      </div>
      <div class="item11">
        <img src="https://picsum.photos/200/300" alt="">
      </div>
      <div class="item12">
        <img src="https://picsum.photos/200/300" alt="">
      </div>
      <div class="item13">
        <img src="https://picsum.photos/200/300" alt="">
      </div>
    </div>

    <div style="text-align: center">
      <a href="{% url 'articleapp:create' %}" class="btn btn-dark rounded-pill col-3 mt-3 mb-3">
        Create Article
      </a>
    </div>

  <script src="{% static 'js/magicgrid.js' %}"></script>

{% endblock %}

CloneCoding_Pinterest/articleapp/templates/articleapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

  <div  style="text-align: center; max-width: 500px; margin: 4rem auto">

    <div class="mb-4">
      <h4>Article Update</h4>
    </div>
    <form action="{% url 'articleapp:update' pk=target_article.pk %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
        <!-- {{ form }} -->
        {% bootstrap_form form %}
      <input type="submit"  class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
  </div>

{% endblock %}